import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Drawer from "@/components/drawer/drawer";

const monserat = Montserrat({
  variable: "--font-monserat",
  subsets: ["latin", 'cyrillic'],
});

const open_sans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin", 'cyrillic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserat.variable} ${open_sans.variable} antialiased bg-white`}
      >
        <Header/>
        <div className="flex">
          <Drawer/>
          {children}
        </div>

      </body>
    </html>
  );
}
